import { requireAuth } from "@/lib/auth/session";
import { getUserWorkspaces } from "@/lib/workspaces/service";
import { getReports } from "@/lib/reports";
import { db } from "@/lib/db";
import { documents } from "@/lib/db/schema";
import { eq } from "drizzle-orm";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import {
  FileSpreadsheet,
  Scale,
  Sparkles,
  MessageSquare,
  ArrowRight,
  Layers,
} from "lucide-react";
import Link from "next/link";
import { redirect } from "next/navigation";
import { ReportCard } from "./report-card";

export default async function ReportsPage({
  searchParams,
}: {
  searchParams: Promise<{ ws?: string }>;
}) {
  const user = await requireAuth();
  const params = await searchParams;
  const workspaces = await getUserWorkspaces(user.id);

  if (workspaces.length === 0) {
    redirect("/workspaces/new");
  }

  const activeWorkspace =
    (params.ws && workspaces.find((w) => w.id === params.ws)) || workspaces[0];

  // Fetch reports for active workspace
  const reportsList = await getReports(activeWorkspace.id);

  // Fetch workspace documents to map IDs to names
  const workspaceDocs = await db
    .select({ id: documents.id, name: documents.name })
    .from(documents)
    .where(eq(documents.workspaceId, activeWorkspace.id));

  const documentNamesMap: Record<string, string> = {};
  for (const doc of workspaceDocs) {
    documentNamesMap[doc.id] = doc.name;
  }

  const summariesCount = reportsList.filter(
    (r) => r.type === "document_summary"
  ).length;
  const comparisonsCount = reportsList.filter(
    (r) => r.type === "document_comparison"
  ).length;

  return (
    <div className="space-y-6 max-w-6xl mx-auto">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 border-b border-border pb-6">
        <div>
          <div className="flex items-center gap-2 mb-1">
            <h1 className="text-2xl font-bold tracking-tight text-foreground">
              Document Intelligence Reports
            </h1>
            <Badge
              variant="outline"
              className="text-xs border-primary/30 bg-primary/10 text-primary"
            >
              Phase 6
            </Badge>
          </div>
          <p className="text-sm text-muted-foreground">
            Structured document summaries, comparisons, and analytical artifacts
            generated by Satori Agent.
          </p>
        </div>

        <Button asChild className="gap-2 shadow-xs shrink-0">
          <Link href={`/chat?ws=${activeWorkspace.id}`}>
            <Sparkles className="h-4 w-4" />
            <span>Generate via Agent</span>
          </Link>
        </Button>
      </div>

      {/* Metrics Bar */}
      <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
        <div className="rounded-xl border border-border bg-card p-4 shadow-2xs">
          <div className="flex items-center gap-2 text-muted-foreground text-xs font-medium">
            <Layers className="h-4 w-4 text-primary" />
            <span>Total Reports</span>
          </div>
          <div className="text-2xl font-bold text-foreground mt-2">
            {reportsList.length}
          </div>
        </div>

        <div className="rounded-xl border border-border bg-card p-4 shadow-2xs">
          <div className="flex items-center gap-2 text-muted-foreground text-xs font-medium">
            <FileSpreadsheet className="h-4 w-4 text-amber-500" />
            <span>Document Summaries</span>
          </div>
          <div className="text-2xl font-bold text-foreground mt-2">
            {summariesCount}
          </div>
        </div>

        <div className="rounded-xl border border-border bg-card p-4 shadow-2xs">
          <div className="flex items-center gap-2 text-muted-foreground text-xs font-medium">
            <Scale className="h-4 w-4 text-indigo-500" />
            <span>Document Comparisons</span>
          </div>
          <div className="text-2xl font-bold text-foreground mt-2">
            {comparisonsCount}
          </div>
        </div>
      </div>

      {/* Reports Grid or Empty State */}
      {reportsList.length === 0 ? (
        <div className="rounded-2xl border border-dashed border-border bg-card p-12 text-center shadow-xs">
          <div className="mx-auto flex h-14 w-14 items-center justify-center rounded-2xl bg-primary/10 text-primary mb-4 shadow-2xs">
            <FileSpreadsheet className="h-7 w-7" />
          </div>
          <h2 className="text-lg font-semibold text-foreground mb-1.5">
            No reports generated yet
          </h2>
          <p className="text-sm text-muted-foreground max-w-md mx-auto mb-6 leading-relaxed">
            Ask Satori Agent in Chat to summarize a document, compare policies
            between files, or compile an executive report.
          </p>
          <div className="flex flex-wrap items-center justify-center gap-3">
            <Button asChild className="gap-2 shadow-xs">
              <Link href={`/chat?ws=${activeWorkspace.id}`}>
                <MessageSquare className="h-4 w-4" />
                <span>Open Chat to Create Report</span>
                <ArrowRight className="h-4 w-4" />
              </Link>
            </Button>
          </div>
        </div>
      ) : (
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-5">
          {reportsList.map((report) => (
            <ReportCard
              key={report.id}
              report={report}
              workspaceId={activeWorkspace.id}
              documentNamesMap={documentNamesMap}
            />
          ))}
        </div>
      )}
    </div>
  );
}
