"use client";

import { useState } from "react";
import { Report } from "@/lib/db/schema";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import {
  FileSpreadsheet,
  Scale,
  Calendar,
  Trash2,
  ExternalLink,
  Loader2,
  FileText,
} from "lucide-react";
import Link from "next/link";
import { deleteReportAction } from "@/app/actions/reports";
import { useRouter } from "next/navigation";

interface ReportCardProps {
  report: Report;
  workspaceId: string;
  documentNamesMap?: Record<string, string>;
}

export function ReportCard({
  report,
  workspaceId,
  documentNamesMap = {},
}: ReportCardProps) {
  const router = useRouter();
  const [isDeleting, setIsDeleting] = useState(false);

  const isComparison = report.type === "document_comparison";
  const TypeIcon = isComparison ? Scale : FileSpreadsheet;

  // Extract preview snippet from content
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const content = report.content as any;
  const previewText =
    content?.summary ||
    content?.executiveSummary ||
    "Structured document analysis generated by Satori Agent.";

  const handleDelete = async (e: React.MouseEvent) => {
    e.preventDefault();
    e.stopPropagation();

    if (!confirm(`Are you sure you want to delete the report "${report.title}"?`)) {
      return;
    }

    setIsDeleting(true);
    try {
      const res = await deleteReportAction(report.id, workspaceId);
      if (res.success) {
        router.refresh();
      } else {
        alert(res.error || "Failed to delete report.");
      }
    } finally {
      setIsDeleting(false);
    }
  };

  return (
    <div className="group relative flex flex-col justify-between rounded-2xl border border-border bg-card p-5 transition-all hover:border-primary/40 hover:shadow-sm">
      <div className="space-y-3">
        {/* Top Badges */}
        <div className="flex items-center justify-between gap-2">
          <Badge
            variant="outline"
            className={`gap-1 px-2.5 py-0.5 text-xs font-medium ${
              isComparison
                ? "bg-indigo-500/10 text-indigo-500 border-indigo-500/20"
                : "bg-amber-500/10 text-amber-500 border-amber-500/20"
            }`}
          >
            <TypeIcon className="h-3 w-3" />
            <span>
              {isComparison ? "Document Comparison" : "Document Summary"}
            </span>
          </Badge>

          <span className="flex items-center gap-1 text-[11px] text-muted-foreground">
            <Calendar className="h-3 w-3" />
            {new Date(report.createdAt).toLocaleDateString(undefined, {
              month: "short",
              day: "numeric",
              year: "numeric",
            })}
          </span>
        </div>

        {/* Title */}
        <h3 className="text-base font-semibold text-foreground group-hover:text-primary transition-colors line-clamp-2">
          <Link href={`/reports/${report.id}`} className="focus:outline-hidden">
            {report.title}
          </Link>
        </h3>

        {/* Preview */}
        <p className="text-xs text-muted-foreground line-clamp-3 leading-relaxed">
          {previewText}
        </p>

        {/* Source Documents tags */}
        {report.sourceDocumentIds && report.sourceDocumentIds.length > 0 && (
          <div className="pt-1 flex flex-wrap items-center gap-1.5">
            {report.sourceDocumentIds.map((docId) => (
              <span
                key={docId}
                className="inline-flex items-center gap-1 rounded-md bg-muted/60 px-2 py-0.5 text-[10px] text-muted-foreground border border-border/50"
              >
                <FileText className="h-2.5 w-2.5" />
                <span className="truncate max-w-[140px]">
                  {documentNamesMap[docId] || "Document"}
                </span>
              </span>
            ))}
          </div>
        )}
      </div>

      {/* Footer actions */}
      <div className="mt-4 pt-3 border-t border-border/60 flex items-center justify-between">
        <Button
          asChild
          variant="ghost"
          size="sm"
          className="h-8 px-2 text-xs font-medium text-primary hover:text-primary/90 gap-1.5"
        >
          <Link href={`/reports/${report.id}`}>
            View Full Report
            <ExternalLink className="h-3 w-3" />
          </Link>
        </Button>

        <Button
          type="button"
          variant="ghost"
          size="sm"
          onClick={handleDelete}
          disabled={isDeleting}
          className="h-8 w-8 p-0 text-muted-foreground hover:text-destructive hover:bg-destructive/10 rounded-lg transition-colors"
          title="Delete report"
        >
          {isDeleting ? (
            <Loader2 className="h-3.5 w-3.5 animate-spin" />
          ) : (
            <Trash2 className="h-3.5 w-3.5" />
          )}
        </Button>
      </div>
    </div>
  );
}
